name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  web:
    name: Web (Parcel) Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: web/package-lock.json

      - name: Install deps
        run: npm install

      - name: Build with Parcel
        run: npm run build

      - name: Upload web artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
